GET http://127.0.0.1:3000/auth
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTcwNDM5OTUzMywiZXhwIjoxNzA0NDAwNDMzfQ.UEb7U5cPyewEWsj27EW-1WwgPLOJs-wU30jhCcjLAbo

